### PR TITLE
[FEAT] CENABLER-5340

### PR DESCRIPTION
**Pull request by Dnikodij**
# Cost Benefit Analyzer

image

image

image

image

image

# Performance Assessment 

image

image

image

image

image

image

image

image

# Recommender

image

image

image

image

### CODE REVIEW

**Comment by nicolaleo** [comment]
"Even it isn't necessary now, it is necessary for the future to introduce translations".=>for the I4N project only english required. Do not work on this for the moment
My question: is it possible to enable hints only if needed? like for example the use of the guide on the right? like "enable hints and guide". I do not like too much text for everyone (even expert users)

**Please stay focused of the list of tasks** (shared doc) to be performed by the end of January. Other things can be added in future BUT we have that deadline to cover everything in the doc. Addidional tasks will be also added to fix topic5 -domain expert- development; these new backend-frontend activities will start from the next sprint 

[DS_toolbox_v3_planning.docx](https://github.com/user-attachments/files/17867844/DS_toolbox_v3_planning.docx)

**Comment by nicolaleo** [comment]
it's ok for me. The hints toggle button should also be present in the other tools pages

**Comment by robraccu** [comment]
It's not clear to me if there are still some hints that are too close to the next input, or if I'm still seeing the old screenshots.... and I'm still seeing the right sidebar overlapping the footer.
Also, for the form and its inputs, some of which are very long, in my opinion we could have an approch similar to this (with a fixed width):

image
image

**Comment by Dnikodij** [comment]
> It's not clear to me if there are still some hints that are too close to the next input, or if I'm still seeing the old screenshots.... and I'm still seeing the right sidebar overlapping the footer. Also, for the form and its inputs, some of which are very long, in my opinion we could have an approch similar to this (with a fixed width):

Only the first two screenshots have the updated space, i dont want to upload another 15 images just for hints. Regarding the sidebar, it must overlap the footer because otherwise it will not push the content to the left, it will be on top of the content which doesnt look good, this is the alternative: 

image

Do you want it to be like this? Also, @nicolaleo

**Comment by nicolaleo** [comment]
In my opion the alternative right sidebar is better now then before. the reduced width form is better also.

**Comment by robraccu** [comment]
> > It's not clear to me if there are still some hints that are too close to the next input, or if I'm still seeing the old screenshots.... and I'm still seeing the right sidebar overlapping the footer. Also, for the form and its inputs, some of which are very long, in my opinion we could have an approch similar to this (with a fixed width):
> 
> Only the first two screenshots have the updated space, i dont want to upload another 15 images just for hints. Regarding the sidebar, it must overlap the footer because otherwise it will not push the content to the left, it will be on top of the content which doesnt look good, this is the alternative:
> 
> image
> Do you want it to be like this? Also, @nicolaleo
> 
> I can reduce the width of the forms so that the right sidebar wont overlap the content of the form, if that is ok?
> 
> Something like this below:
> 
> image image

I think we can reduce the height of the sidebar just for about 50px, its content must scroll in vertical if it is more long. Then it's ok for the width of the form, but it should be positioned in the middle with the sidebar closed and slided to the left with the sidebar open.

**Comment by nicolaleo** [comment]
probably it is better to keep the form width the same between open/closed sidebar. Personal note: I don't like this kind of UI movements (form that slides). 

Please check the ui also with a reduced interface like Ipad

**Comment by robraccu** [comment]
> > > It's not clear to me if there are still some hints that are too close to the next input, or if I'm still seeing the old screenshots.... and I'm still seeing the right sidebar overlapping the footer. Also, for the form and its inputs, some of which are very long, in my opinion we could have an approch similar to this (with a fixed width):
> > 
> > 
> > Only the first two screenshots have the updated space, i dont want to upload another 15 images just for hints. Regarding the sidebar, it must overlap the footer because otherwise it will not push the content to the left, it will be on top of the content which doesnt look good, this is the alternative:
> > image
> > Do you want it to be like this? Also, @nicolaleo
> > I can reduce the width of the forms so that the right sidebar wont overlap the content of the form, if that is ok?
> > Something like this below:
> > image image
> 
> I think we can reduce the height of the sidebar just for about 50px, its content must scroll in vertical if it is more long. Then it's ok for the width of the form, but it should be positioned in the middle with the sidebar closed and slided to the left with the sidebar open.
> 
> @robraccu like this?
> 
> image image

Yes...only one last thing...the width of the form should be the same with the sidebar opened or closed

**Review by nicolaleo — APPROVED** [review]
it's fine

**Review by robraccu — APPROVED** [review]

**Pull request merged**
